env:
  desk: 'base'
  # ui_path: 'ui'
  # zod_path: 'zod'
script:
  - mount:
      - cmd: 'mount %base'
        type: 'urbit:app'
  - build-ui:
      - cmd: '../build-ui.sh'
        type: 'system'
  - commit:
      - cmd: 'commit %base'
        type: 'urbit:app'
  - glob:
      - cmd: '-garden!make-glob %base /dist'
        type: 'urbit:dojo'
