name: Auto-globber

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  boot-fakezod:
    runs-on: ubuntu-latest
    steps:
      - name: Install binary and start fakezod
        run: >
          curl -L https://urbit.org/install/linux-x86_64/latest
          | tar xzk --transform='s/.*/urbit/g'
          && ./urbit -t -F zod

  wait-for-live:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for fakezod
        run: sleep 420s
        shell: bash
  #  - uses: emilioschepis/wait-for-endpoint@v1.0.3
  #    with:
  #      url: http://localhost:8080
  #      method: GET
  #      expected-status: 307  # MOVED: redirects to login page
  #      timeout: 600000
  #      interval: 1000

  bounce:
    runs-on: ubuntu-latest
    needs: [wait-for-live]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
      - name: bounce
        run: >
          chmod 777 ./build-ui.sh
          && git clone https://github.com/tloncorp/bouncer.git
          && cd ./bouncer
          && bundle
          && bin/bounce -c ../bounce-config.yml
