name: Auto-globber

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  auto-glob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'

      - name: Build fakezod, wait, then autoglob
        run: >
          curl -L https://urbit.org/install/linux-x86_64/latest
          | tar xzk --transform='s/.*/urbit/g'
          && ./urbit -t -F zod &
          sleep 600s
          && chmod 777 ./build-ui.sh
          && git clone https://github.com/tloncorp/bouncer.git
          && cd ./bouncer
          && bundle
          && bin/bounce -c ../bounce-config.yml         
